apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: send-email-job
spec:
  schedule: "*/3 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: send-email
            image: buildpack-deps:curl
            args:
            - /bin/sh
            - -ec
            - curl http://server-cluster-ip-service:8080/send_mail
          restartPolicy: Never
